use axum::{
    extract::State,
    http::StatusCode,
    response::Json,
    routing::{get, post},
    Router,
};
use serde::{Deserialize, Serialize};
use crate::services::ai_learning::*;
use crate::services::ai_learning_impl::AiLearningServiceImpl;
use std::sync::Arc;

/// Shared application state containing the AI service
#[derive(Clone)]
pub struct AppState {
    pub ai_service: Arc<AiLearningServiceImpl>,
}

/// Request to ask a question to the AI assistant
#[derive(Debug, Deserialize)]
pub struct AskQuestionRequest {
    pub course_id: String,
    pub question: String,
    pub conversation_history: Option<Vec<Message>>,
}

/// Request to index course content
#[derive(Debug, Deserialize)]
pub struct IndexContentRequest {
    pub course_id: String,
    pub chunks: Vec<ContentChunkInput>,
}

#[derive(Debug, Deserialize)]
pub struct ContentChunkInput {
    pub module_id: Option<String>,
    pub content_type: ContentType,
    pub title: String,
    pub text: String,
    pub metadata: Option<ChunkMetadata>,
}

/// Request to get study recommendations
#[derive(Debug, Deserialize)]
pub struct GetRecommendationsRequest {
    pub course_id: String,
}

/// Request to generate practice questions
#[derive(Debug, Deserialize)]
pub struct GenerateQuestionsRequest {
    pub course_id: String,
    pub topic: String,
    pub count: Option<usize>,
    pub difficulty: Option<Difficulty>,
}

/// Request to summarize a module
#[derive(Debug, Deserialize)]
pub struct SummarizeModuleRequest {
    pub course_id: String,
    pub module_id: String,
}

/// API Response wrapper
#[derive(Debug, Serialize)]
pub struct ApiResponse<T> {
    pub success: bool,
    pub data: Option<T>,
    pub error: Option<String>,
}

impl<T: Serialize> ApiResponse<T> {
    pub fn success(data: T) -> Self {
        Self {
            success: true,
            data: Some(data),
            error: None,
        }
    }
    
    pub fn error(message: String) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(message),
        }
    }
}

/// POST /ask - Ask a question to the AI learning assistant
pub async fn ask_question(
    State(state): State<AppState>,
    Json(body): Json<AskQuestionRequest>,
) -> Result<Json<ApiResponse<AssistantResponse>>, (StatusCode, String)> {
    let query = AssistantQuery {
        user_id: "current_user".to_string(), // Would come from auth context
        course_id: body.course_id.clone(),
        question: body.question.clone(),
        conversation_history: body.conversation_history.clone().unwrap_or_default(),
        context_limit: None,
    };
    
    match state.ai_service.answer_question(query).await {
        Ok(response) => Ok(Json(ApiResponse::success(response))),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// POST /index - Index course content for semantic search
pub async fn index_content(
    State(state): State<AppState>,
    Json(body): Json<IndexContentRequest>,
) -> Result<Json<ApiResponse<serde_json::Value>>, (StatusCode, String)> {
    // Convert input chunks to full ContentChunk objects
    let chunks: Vec<ContentChunk> = body
        .chunks
        .iter()
        .map(|input| ContentChunk {
            id: uuid::Uuid::new_v4().to_string(),
            course_id: body.course_id.clone(),
            module_id: input.module_id.clone(),
            content_type: input.content_type.clone(),
            title: input.title.clone(),
            text: input.text.clone(),
            embedding: vec![], // Will be generated by the service
            metadata: input.metadata.clone().unwrap_or_default(),
            created_at: chrono::Utc::now(),
        })
        .collect();
    
    match state.ai_service.index_course_content(&body.course_id, chunks).await {
        Ok(count) => Ok(Json(ApiResponse::success(serde_json::json!({
            "indexed_count": count,
            "course_id": body.course_id
        })))),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// POST /recommendations - Get personalized study recommendations
pub async fn get_recommendations(
    State(state): State<AppState>,
    Json(body): Json<GetRecommendationsRequest>,
) -> Result<Json<ApiResponse<Vec<StudyRecommendation>>>, (StatusCode, String)> {
    // In production, fetch actual performance data from database
    let performance = StudentPerformance {
        user_id: "current_user".to_string(),
        course_id: body.course_id.clone(),
        overall_score: 0.72,
        completion_rate: 0.65,
        time_spent_minutes: 180,
        quiz_scores: [("quiz1".to_string(), 0.65)].into_iter().collect(),
        assignment_scores: HashMap::new(),
        weak_topics: vec![
            TopicPerformance {
                topic_name: "Linear Algebra".to_string(),
                mastery_score: 0.45,
                question_count: 10,
            },
            TopicPerformance {
                topic_name: "Calculus".to_string(),
                mastery_score: 0.58,
                question_count: 15,
            },
        ],
        strong_topics: vec![
            TopicPerformance {
                topic_name: "Statistics".to_string(),
                mastery_score: 0.89,
                question_count: 12,
            },
        ],
        last_activity: Some(chrono::Utc::now()),
    };
    
    match state.ai_service.generate_recommendations("current_user", &body.course_id, &performance).await {
        Ok(recommendations) => Ok(Json(ApiResponse::success(recommendations))),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// POST /practice-questions - Generate practice questions
pub async fn generate_practice_questions(
    State(state): State<AppState>,
    Json(body): Json<GenerateQuestionsRequest>,
) -> Result<Json<ApiResponse<serde_json::Value>>, (StatusCode, String)> {
    let count = body.count.unwrap_or(5);
    let difficulty = body.difficulty.clone().unwrap_or(Difficulty::Medium);
    
    match state.ai_service.generate_practice_questions(
        &body.course_id,
        &body.topic,
        count,
        difficulty,
    ).await {
        Ok(questions) => Ok(Json(ApiResponse::success(serde_json::json!({
            "questions": questions,
            "topic": body.topic,
            "count": questions.len()
        })))),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// POST /summarize - Summarize a course module
pub async fn summarize_module(
    State(state): State<AppState>,
    Json(body): Json<SummarizeModuleRequest>,
) -> Result<Json<ApiResponse<serde_json::Value>>, (StatusCode, String)> {
    match state.ai_service.summarize_module(&body.course_id, &body.module_id).await {
        Ok(summary) => Ok(Json(ApiResponse::success(serde_json::json!({
            "module_id": body.module_id,
            "course_id": body.course_id,
            "summary": summary
        })))),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// GET /search - Search for relevant course content
#[derive(Debug, Deserialize)]
pub struct SearchQuery {
    pub course_id: String,
    pub query: String,
    pub limit: Option<usize>,
}

pub async fn search_content(
    State(state): State<AppState>,
    query: axum::extract::Query<SearchQuery>,
) -> Result<Json<ApiResponse<serde_json::Value>>, (StatusCode, String)> {
    let limit = query.limit.unwrap_or(10);
    
    match state.ai_service.search_relevant_content(&query.course_id, &query.query, limit).await {
        Ok(chunks) => Ok(Json(ApiResponse::success(serde_json::json!({
            "results": chunks,
            "count": chunks.len()
        })))),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// Create AI assistant router
pub fn ai_router() -> Router<AppState> {
    Router::new()
        .route("/ask", post(ask_question))
        .route("/index", post(index_content))
        .route("/recommendations", post(get_recommendations))
        .route("/practice-questions", post(generate_practice_questions))
        .route("/summarize", post(summarize_module))
        .route("/search", get(search_content))
}
