// Services module - business logic layer
pub mod abac;
pub mod academic;
pub mod ai_learning;
pub mod ai_learning_impl;
pub mod ai_proctoring;
pub mod analytics;
pub mod assessments;
pub mod attendance;
pub mod auth;
pub mod automation;
pub mod backup;
pub mod certificate;
pub mod clearance;
pub mod code_sandbox;
pub mod communication;
pub mod compliance;
pub mod course_builder;
pub mod courses;
pub mod developer;
pub mod employer;
pub mod fee;
pub mod gamification;
pub mod import_;
pub mod jwt;
pub mod library;
pub mod license;
pub mod live;
pub mod migration;
pub mod ml;
pub mod onboarding;
pub mod peer_review;
pub mod portfolio;
pub mod proctoring;
pub mod rbac;
pub mod research;
pub mod security;
pub mod security_audit;
pub mod signup;
pub mod sso;
pub mod timetable;
pub mod upgrade;
pub mod video;
pub mod wellbeing;
pub mod whitelabel;

pub use auth::{change_password, login, register, request_password_reset, reset_password};
pub use import_::service::{generate_csv_template, import_users_from_csv};
